### ISSUE TITLE
CRUD Gestational Age Tracking

### ISSUE THREAD

**Issue by mdcg** [sigmages/pregnancy-tracking-API#5]
- [ ] Creation of Gestational Age Tracking models
- [ ] Creation of Change History models (Audit)
- [ ] Implement CRUD serializers
- [ ] Implement CRUD views
- [ ] Tests!

!!! **Points of attention:**
- Only authenticated users can use this CRUD
- Every change at Gestational Age Tracking's data must be saved in a history (CREATED, UPDATED)
- It cannot be deleted (soft delete)
